spring.application.name=minimarket
server.port=8080

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Configuracion de H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# HikariCP (ajustes recomendados)
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones adicionales
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

info.app.name="Mi microservicio de ejemplo"
info.app.description="Este es un microservicio de ejemplo para demostrar el uso de Spring Boot y Oracle Database."
info.app.version=1.0.0

spring.security.user.name=admin
spring.security.user.password=admin123

# JWT
jwt.secret=aK7mP2nL9qR5tW8xY3bD6vF4hJ1cG0sZ8eN4wM7uO9iT2aB5kL3dP6jH8rX1vC4fE
jwt.expiration=3600000